CREATE TABLE group_user (
	GROUP_USER_ID int(11) NOT NULL,
	GROUP_COD varchar(3) NOT NULL,
	DESCRIPCION varchar (100) DEFAULT NULL
) ;

CREATE TABLE login_user (
	ID_USER int(11) NOT NULL,
	USERNAME varchar(20) NOT NULL,
	PASSWORD varchar (20) NOT NULL,
	GROUP_USER_ID int (11) NOT NULL,
	EMAIL varchar(200) DEFAULT NULL,
	NAME varchar(100) DEFAULT NULL,
	LASTNAME varchar(100) DEFAULT NULL

);
